<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS Customer Registration</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>74c321ad-b150-4933-bbc0-893d2c91eea3</testSuiteGuid>
   <testCaseLink>
      <guid>3600c6d8-7301-43b3-96c0-6dd66526fa30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/Case Registration/TC Verification Mobile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>f3e3f772-9d8c-4c7c-81ce-387f7a889513</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Internal Data/Verification Mobile Data</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>f3e3f772-9d8c-4c7c-81ce-387f7a889513</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>ReferenceID</value>
         <variableId>5e43a958-5983-4b2e-8b95-63e69b53d627</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>f3e3f772-9d8c-4c7c-81ce-387f7a889513</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>isApprove</value>
         <variableId>345b22ec-9504-45c7-a744-4c7cf8b8e287</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1217ff5b-5a50-4d03-ad16-f62282c8765c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/Case Registration/TC Delivery Prio Mobile</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>3ea1bc80-affe-4a5f-a404-799d0630df77</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Internal Data/Delivery Prio Mobile</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>3ea1bc80-affe-4a5f-a404-799d0630df77</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Refid</value>
         <variableId>d7b66373-6960-459a-a743-7583e27206a3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3ea1bc80-affe-4a5f-a404-799d0630df77</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>iccid</value>
         <variableId>a3f30ff0-fe85-499d-b5a3-96761fd3e0cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e74ccf8-573d-4022-9a32-18670a62fee7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>edf7a0aa-e1b5-4a91-a6b7-3198b204602d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42761104-6274-422c-b0b8-c1c1e97ab382</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>46f5957e-6b5f-4811-b64c-da649fe66f00</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ab4f2ab2-e1c4-45a7-962f-98d278b7408d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d3b8cbdd-8dc0-4bf2-9300-56fe8c91b735</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f066183a-11d4-45f0-a75a-c14d464fb01e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f850dc65-c0be-45ba-bc75-d82ca3058f82</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>3ea1bc80-affe-4a5f-a404-799d0630df77</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>CourierPartner</value>
         <variableId>dc00be93-c18b-4e54-bed1-2bed35fc5c96</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
