<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS02 Approve Reactivation XLC Online</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>2cd51fd0-8787-4581-bab0-d6625e068bdf</testSuiteGuid>
   <testCaseLink>
      <guid>6ea23c55-9586-44c1-83b9-c5f832ea78d3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reused TC/2. Credential/Login</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>1cdd0bb4-6534-42d9-b3c6-815333489f8c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/Internal Data/User Login</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/User Login&quot;).getValue(1, 2)</value>
         <variableId>f9120fb1-16d7-4165-9d18-cb40c9466188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/User Login&quot;).getValue(2, 2)</value>
         <variableId>cf377009-073d-4c48-bfb5-5ffff981f3e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cec35a1a-f805-4be9-8f86-819ad9104784</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO001 Filter based on TicketID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/Data verification in XLC Approval&quot;).getValue(1, 2)</value>
         <variableId>bcdda617-e659-4e04-bd38-511b52bc4ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b61fe5b-3527-4e89-8bbd-0721c4cb846c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cbe075-df66-4133-ae32-cee9fbae1cdf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c127714a-3105-433b-858b-ddde9b83ac12</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO002a Update and verification Data Reactivation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2bee055-0513-4c44-8fc8-53dada517f33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac387550-1e82-4e76-8b02-be2dbe672570</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd60c07-360d-42f0-ac5d-17a6d45e3ed7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91798560-c487-4594-8f05-df694edbbff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>652099c2-31a0-4018-b980-cbe48895bc7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d95e2a2-2e16-4568-a334-598741cb038c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d4f67a9-bead-47e7-82f7-57781225cf0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbb71ba1-8ae9-4be2-a27e-49d9db091c1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28f92aa5-59ae-4e87-a6d8-5d0fdb858e88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b5e67294-b6a5-4f6d-8267-c05579c0c8d6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO003a Approve transaction</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed4bff1b-9a92-4191-bb91-ad367fcda76d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6737f36e-319f-48fc-bc01-5238dddbf745</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7260f10e-23dd-45c7-b8cb-c3a24864f7e8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
