<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS03 Reject Reactivation XLC Online</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>f86695af-0128-45c8-896b-557cf97ed280</testSuiteGuid>
   <testCaseLink>
      <guid>29741684-27bd-4160-b82c-bf24ecc3aa98</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reused TC/2. Credential/Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/User Login&quot;).getValue(1, 2)</value>
         <variableId>f9120fb1-16d7-4165-9d18-cb40c9466188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/User Login&quot;).getValue(2, 2)</value>
         <variableId>cf377009-073d-4c48-bfb5-5ffff981f3e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1f184d30-cc75-4fc4-8835-635881621b75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO001 Filter based on TicketID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/Data verification in XLC Approval&quot;).getValue(1, 1)</value>
         <variableId>bcdda617-e659-4e04-bd38-511b52bc4ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4b61fe5b-3527-4e89-8bbd-0721c4cb846c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cbe075-df66-4133-ae32-cee9fbae1cdf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>61aeab51-5911-4ecd-a2cc-68853c399307</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO002a Update and verification Data Reactivation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a2bee055-0513-4c44-8fc8-53dada517f33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac387550-1e82-4e76-8b02-be2dbe672570</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bdd60c07-360d-42f0-ac5d-17a6d45e3ed7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91798560-c487-4594-8f05-df694edbbff1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>652099c2-31a0-4018-b980-cbe48895bc7a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d95e2a2-2e16-4568-a334-598741cb038c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7d4f67a9-bead-47e7-82f7-57781225cf0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbb71ba1-8ae9-4be2-a27e-49d9db091c1a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>28f92aa5-59ae-4e87-a6d8-5d0fdb858e88</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ac5f11af-b1b9-4afb-8b30-2614779cfa7d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO003b Reject transaction</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/Data verification in XLC Approval&quot;).getValue(1, 1)</value>
         <variableId>56205f52-6e4f-45fe-aa1f-2a9c10af5d6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>e7d1b078-c6e8-4f27-afa2-bf631b34847e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>null</value>
         <variableId>686cf127-7b17-43fc-9810-dd72a3f80d04</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
