<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS05 Reject Replacement XLC Online</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>6ce5ced4-de5c-418b-b2bc-7dd5e884f57a</testSuiteGuid>
   <testCaseLink>
      <guid>02470ecb-528e-4721-ad7f-a852f87a8815</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Reused TC/2. Credential/Login</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/User Login&quot;).getValue(1, 2)</value>
         <variableId>f9120fb1-16d7-4165-9d18-cb40c9466188</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/User Login&quot;).getValue(2, 2)</value>
         <variableId>cf377009-073d-4c48-bfb5-5ffff981f3e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>97e153f3-6c68-4717-9d34-14406aba0264</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO001 Filter based on TicketID</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/Data verification in XLC Approval&quot;).getValue(1, 4)</value>
         <variableId>bcdda617-e659-4e04-bd38-511b52bc4ab5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/Data verification in XLC Approval&quot;).getValue(2, 3)</value>
         <variableId>4b61fe5b-3527-4e89-8bbd-0721c4cb846c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e3cbe075-df66-4133-ae32-cee9fbae1cdf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33243776-4570-4ff3-a3c9-a004ed390eee</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO002b Update and verification Data Replacement</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>SCRIPT_VARIABLE</type>
         <value>findTestData(&quot;Internal Data/Data verification in XLC Approval&quot;).getValue(4, 1)</value>
         <variableId>41864c62-016b-4d5e-b442-97b8d4c32657</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5aa9b869-719e-42d8-b66b-ef34142fe56f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>146c82a4-3596-4aab-beb4-b9004a70dd44</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9cf6a15a-a813-40f1-818c-b50e1e7d6e40</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85d3d7b7-d0e8-4a0c-a510-b8a1ab43d217</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>880cc6ff-da09-49a3-ad63-c21f6076739b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5adcec1d-c0f7-4ce5-adc7-5d9ba42b87ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b097c7d6-f388-4be3-b663-a13e73627429</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e15f87f-cc4d-498f-a1b2-361e01312294</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cb554ec3-a5a5-4763-89fc-14c703ebf0d7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8dc5d75a-5f42-4dab-9def-8cc6b6bff4da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Main TC/XLC Approval/XLCO003b Reject transaction</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>56205f52-6e4f-45fe-aa1f-2a9c10af5d6e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7d1b078-c6e8-4f27-afa2-bf631b34847e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>686cf127-7b17-43fc-9810-dd72a3f80d04</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
